CREATE DATABASE IF NOT EXISTS alx_book_store;

USE alx_book_store;

CREATE TABLE Authors (
    author_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    author_name VARCHAR(215) NOT NULL,
    PRIMARY KEY (author_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Customers (
    customer_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_name VARCHAR(215) NOT NULL,
    email VARCHAR(215) NOT NULL,
    address TEXT,
    PRIMARY KEY (customer_id),
    UNIQUE KEY UQ_CUSTOMERS_EMAIL (email)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Books (
    book_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(130) NOT NULL,
    author_id INT UNSIGNED NOT NULL,
    price DOUBLE NOT NULL,
    publication_date DATE NOT NULL,
    PRIMARY KEY (book_id),
    KEY IDX_BOOKS_AUTHOR_ID (author_id),
    CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (author_id)
        REFERENCES AUTHORS (author_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Orders (
    order_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id INT UNSIGNED NOT NULL,
    order_date DATE NOT NULL,
    PRIMARY KEY (order_id),
    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE Order_Details (
    orderdetailid INT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id INT UNSIGNED NOT NULL,
    book_id INT UNSIGNED NOT NULL,
    quantity DOUBLE NOT NULL,
    PRIMARY KEY (orderdetailid),
    KEY IDX_ORDER_DETAILS_ORDER_ID (order_id),
    KEY IDX_ORDER_DETAILS_BOOK_ID (book_id),
    CONSTRAINT FK_ORDER_DETAILS_ORDERS FOREIGN KEY (order_id)
        REFERENCES ORDERS (order_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_ORDER_DETAILS_BOOKS FOREIGN KEY (book_id)
        REFERENCES BOOKS (book_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;